package selenium_IDE_Practice;



//Generated by Selenium IDE

import org.junit.Test;

import org.junit.Before;

import org.junit.After;

import static org.junit.Assert.*;

import static org.hamcrest.CoreMatchers.is;

import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;

import org.openqa.selenium.WebDriver;

import org.openqa.selenium.firefox.FirefoxDriver;

import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;

import org.openqa.selenium.remote.DesiredCapabilities;

import org.openqa.selenium.Dimension;

import org.openqa.selenium.WebElement;

import org.openqa.selenium.interactions.Actions;

import org.openqa.selenium.support.ui.ExpectedConditions;

import org.openqa.selenium.support.ui.WebDriverWait;

import org.openqa.selenium.JavascriptExecutor;

import org.openqa.selenium.Alert;

import org.openqa.selenium.Keys;

import java.util.*;

import java.net.MalformedURLException;

import java.net.URL;



public class Test_01 {

  private WebDriver driver;

  private Map<String, Object> vars;

  JavascriptExecutor js;



  @Before

  public void setUp() {

      

      

      

      //System.setProperty("webdriver.chrome.driver", "C:/Users/Student/Downloads/chromedriver_win32/chromedriver.exe");
      
      //System.setProperty("webdriver.edge.driver", "C:/Users/Student/Downloads/edgedriver_win64/msedgedriver.exe");

      //driver = new ChromeDriver();

     // driver = new EdgeDriver();
      
      
      
      System.setProperty("webdriver.gecko.driver", "C:/Users/Student/Downloads/geckodriver-v0.32.0-win-aarch64.zip/geckodriver.exe");

      driver = new FirefoxDriver();

      

      js = (JavascriptExecutor) driver;

      vars = new HashMap<String, Object>();

  }



  @After

  public void tearDown() {

      driver.quit();

  }



  @Test

  public void login() throws Exception {

      driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");

      

      

      //sync

      Thread.sleep(3000);

      

      assertThat(driver.getTitle(), is("OrangeHRM"));

      driver.findElement(By.name("username")).sendKeys("Admin");

      driver.findElement(By.name("password")).sendKeys("admin123");

      driver.findElement(By.cssSelector(".oxd-button")).click();

      assertThat(driver.findElement(By.cssSelector(".oxd-text--h6")).getText(), is("PIM"));

      driver.findElement(By.cssSelector(".oxd-userdropdown-tab")).click();

      

      //sync

      Thread.sleep(3000);

      

      driver.findElement(By.linkText("Logout")).click();

      assertThat(driver.findElement(By.cssSelector(".orangehrm-login-forgot-header")).getText(),

              is("Forgot your password?"));

      assertThat(driver.getTitle(), is("OrangeHRM"));

  }

}

